# name: build and deploy aliyun

# on:
#   push:
#     branches: [main]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: false
#       - name: Install and Build
#         run: |
#           cd client
#           npm install
#           npm run build
#       - name: Deploy to aliyun server
#         uses: easingthemes/ssh-deploy@main
#         with:
#           SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
#           ARGS: "-avz --delete --verbose"
#           EXCLUDE: "/client/node_modules/, /server/node_modules/, /.git/"
#           SOURCE: "./"
#           REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
#           REMOTE_USER: "root"
#           TARGET: "/root/repo/github/gpt-code-gen/"
#           SCRIPT_BEFORE: |
#             rm -rf /root/repo/github/gpt-code-gen/
#             mkdir -p /root/repo/github/gpt-code-gen/
#           SCRIPT_AFTER: |
#             cd /root/repo/github/gpt-code-gen
#             docker-compose down --rmi all
#             docker-compose up
